import PresetPlayer from "./index-umd";
import Player from "./player";
import BasePlugin from "./plugin/basePlugin";
import Plugin from "./plugin/plugin";
import * as Events from "./events";
import Errors from "./error";
import Sniffer from "./utils/sniffer";
import Util from "./utils/util";
import STATE_CLASS from "./stateClassMap";
import I18N from "./lang/i18n";
import { STATES } from "./state";
export { PresetPlayer as default, Player as SimplePlayer, BasePlugin, Plugin, Events, Errors, Sniffer, Util, STATE_CLASS, I18N, STATES };
