export type IBasePluginOptions = import('./plugin/basePlugin').IBasePluginOptions;
export type IPluginOptions = import('./plugin/plugin').IPluginOptions;
export type IPlayerOptions = import('./defaultConfig').IPlayerOptions;
export type IError = import('./error').IError;
export type IXGI18nText = import('./lang/i18n').IXGI18nText;
import PresetPlayer from "./index-umd";
import Player from "./player";
import Plugin from "./plugin/plugin";
import BasePlugin from "./plugin/basePlugin";
import * as Events from "./events";
import Errors from "./error";
import Sniffer from "./utils/sniffer";
import Util from "./utils/util";
import STATE_CLASS from "./stateClassMap";
import I18N from "./lang/i18n";
export { PresetPlayer as default, Player as SimplePlayer, Plugin, BasePlugin, Events, Errors, Sniffer, Util, STATE_CLASS, I18N };
